FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
# Generate Prisma Client before the build
COPY . .
RUN bun run db:generate


# Ensure DATABASE_URL is available
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run" ,"start:web" ]